plot4<-function(){
        temp <- tempfile()
        download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
        entire_file <- read.csv2(unz(temp, "household_power_consumption.txt"),stringsAsFactors=FALSE )
        unlink(temp)
        entire_file<-transform(entire_file,Date=as.Date(Date,"%d/%m/%Y"))
        feb_data <- subset(entire_file, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
        feb_data1<-within(feb_data, { timestamp=as.POSIXct(paste(Date, Time)) })
        png("~/Desktop/Coursera/plot4.png", width = 480, height = 480)
        par(mfrow=c(2,2))
        plot(Global_active_power~timestamp,feb_data1,ylab="Global Active Power",xlab="",pch=".:")
        lines(Global_active_power~timestamp,feb_data1)
        plot(Voltage~timestamp,feb_data1,ylab="Voltage",xlab="datetime",pch=".:")
        lines(Voltage~timestamp,feb_data1,lwd=1)
        plot(Sub_metering_1~timestamp,feb_data1,ylab="Energy sub metering",xlab="",type="n")
        points(Sub_metering_1~timestamp,feb_data1,pch=".:")
        lines(Sub_metering_1~timestamp,feb_data1)
        points(Sub_metering_2~timestamp,feb_data1,pch=".:",col="red")
        lines(Sub_metering_2~timestamp,feb_data1,col="red")
        points(Sub_metering_3~timestamp,feb_data1,pch=".:",col="blue")
        lines(Sub_metering_3~timestamp,feb_data1,col="blue")
        legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lwd=1,bty = "n")
        plot(Global_reactive_power~timestamp,feb_data1,ylab="Global_reactive_power",xlab="datetime",pch=".:")
        lines(Global_reactive_power~timestamp,feb_data1)
        dev.off()
}